#+TITLE: HTTP Fundamentals

* bronnen
  [[https://www.pluralsight.com/courses/xhttp-fund][HTTP Fundamentals door Scott Allen]]
* HTTP Resources
  Een URL heeft de volgende vorm:

  http://food.com:80/recipes/squash

  De onderdelen van een URL hebben de volgende namen:
  - url scheme: http:
  - host: food.com
  - port: 80
  - url path: /recipes/squash

  http://bing.com/search?q=jaboticaba

  - query: q=jaboticaba

  http://wikipedia.org/wiki/jabuticaba#Description

  - fragment: description

  Het fragment wordt alleen gebruikt door de browser om een heading
  binnen een pagina te lokaliseren.
** URL safe characters
   [a-zA-Z0-9]
   [$-_.+*'(),]

   Percent encoded / URL encoded wordt gebruikt om unsafe characters
   in een URL te coderen:

   - space: %20
   - !: %21
   - ": %22

   Getallen in percent encoding zijn in hexadecimale notatie!
** Mime types
   HTTP gebruikt MIME types o het soort content te duiden:
   
   | Type/Subtype | Description |
   |--------------+-------------|
   | images/gif   | GIF image   |
   | image/png    | PNG image   |
   | text/xml     | XML         |
   | text/plain   | just text   |
   | text/html    | HTML        |
   | .            |             |
   | .            |             |
   | .            |             |
   | enzovoort    |             |
   

   Mime was oorspronkelijk bedoeld voor email.
** Content negotiation
   Browser kan specificeren welke type content het wil ontvangen.
** Conclusion
   Tot nu toe hebben we behandeld:
   - resources
   - URL
   - Representation
* HTTP Messages
* HTTP Connections
* HTTP Architecture
* HTTP Security
